import { createFileRoute } from "@tanstack/react-router";
import { useEffect,useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { PageState } from "@/components/prazocontabil/ui";
import { WorkspaceData,emptyWorkspaceData,fetchWorkspaceData,modeloEmailPadrao } from "@/lib/prazocontabil-data";
export const Route=createFileRoute("/app/configuracoes")({head:()=>({meta:[{title:"Configurações — PrazoContábil"},{name:"description",content:"Configuração funcional de e-mails, modelos e frequências de alertas."}]}),component:ConfiguracoesPage});
function ConfiguracoesPage(){const[data,setData]=useState<WorkspaceData>(emptyWorkspaceData());const[loading,setLoading]=useState(true);const[error,setError]=useState("");useEffect(()=>{fetchWorkspaceData().then(setData).catch(()=>setError("Não foi possível carregar as configurações.")).finally(()=>setLoading(false))},[]);if(loading||error)return <PageState loading={loading} error={error}/>;const cfg=data.configuracao;return <div className="space-y-5"><section className="surface-card rounded-lg border p-5"><h2 className="text-xl font-semibold">Configuração de e-mails e alertas</h2><p className="mt-1 text-sm text-muted-foreground">Edite o modelo e as frequências salvas no banco para avisos de vencimento.</p></section><section className="surface-card rounded-lg border p-5"><div className="grid gap-4 md:grid-cols-2"><label className="flex items-center gap-2 text-sm"><input type="checkbox" defaultChecked={cfg?.alerta30Dias??true}/> Alertar 30 dias antes</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" defaultChecked={cfg?.alerta15Dias??true}/> Alertar 15 dias antes</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" defaultChecked={cfg?.alerta7Dias??true}/> Alertar 7 dias antes</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" defaultChecked={cfg?.alertaNoVencimento??true}/> Alertar no dia do vencimento</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" defaultChecked={cfg?.alertaPosVencido??true}/> Ativar alerta pós-vencido</label><div><label className="text-sm font-medium">Frequência pós-vencido em dias</label><Input type="number" defaultValue={cfg?.repetirVencidoDias??5}/></div><div className="md:col-span-2"><label className="text-sm font-medium">Assunto padrão do e-mail</label><Input defaultValue={cfg?.assuntoPadrao??modeloEmailPadrao.assunto}/></div><div className="md:col-span-2"><label className="text-sm font-medium">Corpo padrão do e-mail</label><Textarea className="min-h-72" defaultValue={cfg?.corpoPadrao??modeloEmailPadrao.corpo}/></div><div className="md:col-span-2"><label className="text-sm font-medium">Assinatura do escritório</label><Input defaultValue={cfg?.assinaturaEscritorio??"Equipe PrazoContábil"}/></div></div><div className="mt-5 flex flex-wrap gap-2"><Button>Salvar configurações</Button><Button variant="outline">Enviar e-mail de teste</Button><Button variant="outline">Restaurar modelo padrão</Button></div></section></div>}
