/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPainelRouteImport } from './routes/app.painel'
import { Route as AppEmpresasRouteImport } from './routes/app.empresas'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPainelRoute = AppPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpresasRoute = AppEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/empresas': typeof AppEmpresasRoute
  '/app/painel': typeof AppPainelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/empresas': typeof AppEmpresasRoute
  '/app/painel': typeof AppPainelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/empresas': typeof AppEmpresasRoute
  '/app/painel': typeof AppPainelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app' | '/app/empresas' | '/app/painel'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/app/empresas' | '/app/painel'
  id: '__root__' | '/' | '/app' | '/app/empresas' | '/app/painel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/painel': {
      id: '/app/painel'
      path: '/painel'
      fullPath: '/app/painel'
      preLoaderRoute: typeof AppPainelRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/empresas': {
      id: '/app/empresas'
      path: '/empresas'
      fullPath: '/app/empresas'
      preLoaderRoute: typeof AppEmpresasRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppEmpresasRoute: typeof AppEmpresasRoute
  AppPainelRoute: typeof AppPainelRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEmpresasRoute: AppEmpresasRoute,
  AppPainelRoute: AppPainelRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
