/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRotinasRouteImport } from './routes/app.rotinas'
import { Route as AppPainelRouteImport } from './routes/app.painel'
import { Route as AppObrigacoesRouteImport } from './routes/app.obrigacoes'
import { Route as AppEmpresasRouteImport } from './routes/app.empresas'
import { Route as AppDocumentosRouteImport } from './routes/app.documentos'
import { Route as AppEmpresasRouteImport } from './routes/app.empresas.'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRotinasRoute = AppRotinasRouteImport.update({
  id: '/rotinas',
  path: '/rotinas',
  getParentRoute: () => AppRoute,
} as any)
const AppPainelRoute = AppPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AppRoute,
} as any)
const AppObrigacoesRoute = AppObrigacoesRouteImport.update({
  id: '/obrigacoes',
  path: '/obrigacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpresasRoute = AppEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentosRoute = AppDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpresasRoute = AppEmpresasRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEmpresasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/documentos': typeof AppDocumentosRoute
  '/app/empresas': typeof AppEmpresasRouteWithChildren
  '/app/obrigacoes': typeof AppObrigacoesRoute
  '/app/painel': typeof AppPainelRoute
  '/app/rotinas': typeof AppRotinasRoute
  '/app/empresas/': typeof AppEmpresasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/documentos': typeof AppDocumentosRoute
  '/app/obrigacoes': typeof AppObrigacoesRoute
  '/app/painel': typeof AppPainelRoute
  '/app/rotinas': typeof AppRotinasRoute
  '/app/empresas': typeof AppEmpresasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/documentos': typeof AppDocumentosRoute
  '/app/empresas': typeof AppEmpresasRouteWithChildren
  '/app/obrigacoes': typeof AppObrigacoesRoute
  '/app/painel': typeof AppPainelRoute
  '/app/rotinas': typeof AppRotinasRoute
  '/app/empresas/': typeof AppEmpresasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/documentos'
    | '/app/empresas'
    | '/app/obrigacoes'
    | '/app/painel'
    | '/app/rotinas'
    | '/app/empresas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/documentos'
    | '/app/obrigacoes'
    | '/app/painel'
    | '/app/rotinas'
    | '/app/empresas'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/documentos'
    | '/app/empresas'
    | '/app/obrigacoes'
    | '/app/painel'
    | '/app/rotinas'
    | '/app/empresas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/rotinas': {
      id: '/app/rotinas'
      path: '/rotinas'
      fullPath: '/app/rotinas'
      preLoaderRoute: typeof AppRotinasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/painel': {
      id: '/app/painel'
      path: '/painel'
      fullPath: '/app/painel'
      preLoaderRoute: typeof AppPainelRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/obrigacoes': {
      id: '/app/obrigacoes'
      path: '/obrigacoes'
      fullPath: '/app/obrigacoes'
      preLoaderRoute: typeof AppObrigacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/empresas': {
      id: '/app/empresas'
      path: '/empresas'
      fullPath: '/app/empresas'
      preLoaderRoute: typeof AppEmpresasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documentos': {
      id: '/app/documentos'
      path: '/documentos'
      fullPath: '/app/documentos'
      preLoaderRoute: typeof AppDocumentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/empresas/': {
      id: '/app/empresas/'
      path: '/'
      fullPath: '/app/empresas/'
      preLoaderRoute: typeof AppEmpresasRouteImport
      parentRoute: typeof AppEmpresasRoute
    }
  }
}

interface AppEmpresasRouteChildren {
  AppEmpresasRoute: typeof AppEmpresasRoute
}

const AppEmpresasRouteChildren: AppEmpresasRouteChildren = {
  AppEmpresasRoute: AppEmpresasRoute,
}

const AppEmpresasRouteWithChildren = AppEmpresasRoute._addFileChildren(
  AppEmpresasRouteChildren,
)

interface AppRouteChildren {
  AppDocumentosRoute: typeof AppDocumentosRoute
  AppEmpresasRoute: typeof AppEmpresasRouteWithChildren
  AppObrigacoesRoute: typeof AppObrigacoesRoute
  AppPainelRoute: typeof AppPainelRoute
  AppRotinasRoute: typeof AppRotinasRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDocumentosRoute: AppDocumentosRoute,
  AppEmpresasRoute: AppEmpresasRouteWithChildren,
  AppObrigacoesRoute: AppObrigacoesRoute,
  AppPainelRoute: AppPainelRoute,
  AppRotinasRoute: AppRotinasRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
